/**
 * Persona Demo Page
 *
 * Showcases persona components with sample data
 * Navigate to /persona-demo to view
 */

'use client'

import React from 'react'
import { PersonaAvatar, PersonaBadge, ExampleCard } from '@/components/persona'
import { getPersonaById } from '@/data/personas'
import { Example } from '@/types/vocabulary'

export default function PersonaDemoPage() {
  // Sample examples using demo data structure
  const sampleExamples: Example[] = [
    {
      japanese: '毎朝６時に起きます。',
      kana: 'まいあさろくじにおきます。',
      english: 'I wake up at 6 every morning.',
      source: {
        type: 'generated',
        persona: 'persona_ken',
        model: 'claude-sonnet-4-20250514',
        generatedAt: '2025-10-29T23:30:00Z',
      },
      license: {
        text: 'Generated by LingoMemory',
        url: '',
      },
      needsReview: true,
      validation: {
        tokenMatch: true,
        kanaMatch: true,
        lengthOk: true,
        autoScore: 0.95,
        validatedAt: '2025-10-29T23:30:01Z',
      },
    },
    {
      japanese: '週末は楽しいです。',
      kana: 'しゅうまつはたのしいです。',
      english: 'Weekends are fun.',
      source: {
        type: 'generated',
        persona: 'persona_aya',
        model: 'claude-sonnet-4-20250514',
        generatedAt: '2025-10-29T23:30:04Z',
      },
      license: {
        text: 'Generated by LingoMemory',
        url: '',
      },
      needsReview: false,
      validation: {
        tokenMatch: true,
        kanaMatch: true,
        lengthOk: true,
        autoScore: 0.94,
        validatedAt: '2025-10-29T23:30:05Z',
      },
    },
    {
      japanese: '水を飲みます',
      kana: 'みずをのみます',
      english: 'I drink water',
      source: {
        type: 'tatoeba',
        id: '204677',
      },
      license: {
        text: 'CC BY 2.0',
        url: 'https://creativecommons.org/licenses/by/2.0/',
      },
    },
  ]

  const kenPersona = getPersonaById('persona_ken')
  const ayaPersona = getPersonaById('persona_aya')

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
      <div className="max-w-4xl mx-auto">
        {/* Header */}
        <div className="bg-white rounded-lg shadow-sm p-6 mb-8">
          <h1 className="text-3xl font-bold text-gray-900 mb-2">
            🎌 Persona System Demo
          </h1>
          <p className="text-gray-600">
            Preview of persona-based example display components
          </p>
        </div>

        {/* Avatar Demo */}
        <div className="bg-white rounded-lg shadow-sm p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Persona Avatars
          </h2>
          <div className="flex flex-wrap gap-6">
            {kenPersona && (
              <div>
                <p className="text-sm text-gray-500 mb-2">Small</p>
                <PersonaAvatar persona={kenPersona} size="sm" showName />
              </div>
            )}
            {kenPersona && (
              <div>
                <p className="text-sm text-gray-500 mb-2">Medium</p>
                <PersonaAvatar persona={kenPersona} size="md" showName />
              </div>
            )}
            {ayaPersona && (
              <div>
                <p className="text-sm text-gray-500 mb-2">Large</p>
                <PersonaAvatar persona={ayaPersona} size="lg" showName />
              </div>
            )}
          </div>
        </div>

        {/* Badge Demo */}
        <div className="bg-white rounded-lg shadow-sm p-6 mb-6">
          <h2 className="text-xl font-semibold text-gray-900 mb-4">
            Status Badges
          </h2>
          <div className="space-y-3">
            <div>
              <p className="text-sm text-gray-500 mb-2">Source Types</p>
              <div className="flex flex-wrap gap-2">
                <PersonaBadge type="source" status="generated" />
                <PersonaBadge type="source" status="authentic" />
                <PersonaBadge type="source" status="tatoeba" />
                <PersonaBadge type="source" status="jmdict" />
                <PersonaBadge type="source" status="custom" />
              </div>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-2">Review Status</p>
              <div className="flex flex-wrap gap-2">
                <PersonaBadge type="review" status="approved" />
                <PersonaBadge type="review" status="needs_review" />
                <PersonaBadge type="review" status="rejected" />
              </div>
            </div>
            <div>
              <p className="text-sm text-gray-500 mb-2">Validation</p>
              <div className="flex flex-wrap gap-2">
                <PersonaBadge type="validation" status="passed" />
                <PersonaBadge type="validation" status="failed" />
                <PersonaBadge type="validation" status="warning" />
              </div>
            </div>
          </div>
        </div>

        {/* Example Card Demo */}
        <div className="space-y-6">
          <h2 className="text-xl font-semibold text-gray-900">
            Example Cards
          </h2>

          {/* Generated Example with Validation */}
          <div>
            <h3 className="text-sm font-medium text-gray-700 mb-3">
              Generated Example (With Validation)
            </h3>
            <ExampleCard
              example={sampleExamples[0]}
              persona={kenPersona}
              showValidation={true}
            />
          </div>

          {/* Generated Example without Validation */}
          <div>
            <h3 className="text-sm font-medium text-gray-700 mb-3">
              Generated Example (Simple)
            </h3>
            <ExampleCard
              example={sampleExamples[1]}
              persona={ayaPersona}
              showValidation={false}
            />
          </div>

          {/* Authentic Example */}
          <div>
            <h3 className="text-sm font-medium text-gray-700 mb-3">
              Authentic Example
            </h3>
            <ExampleCard example={sampleExamples[2]} />
          </div>
        </div>

        {/* Footer */}
        <div className="mt-12 text-center text-sm text-gray-500">
          <p>✨ Persona components ready for integration</p>
          <p className="mt-2">
            Navigate to <code className="bg-gray-100 px-2 py-1 rounded">/persona-demo</code> to view this page
          </p>
        </div>
      </div>
    </div>
  )
}
